import io.gitlab.arturbosch.detekt.Detekt

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-parcelize'
    id 'androidx.navigation.safeargs.kotlin'
    id 'com.google.devtools.ksp'
    id 'io.gitlab.arturbosch.detekt'
}

apply from: file("$rootDir/libraries.gradle")
apply from: file("$rootDir/ktlint.gradle")
//apply from: file("$rootDir/detekt.gradle")

android {
    namespace 'com.codestracture'
    compileSdk 35

    defaultConfig {
        applicationId "com.codestracture"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"

       // testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField 'String', 'BASE_URL', "\"https://portal.courtesycarsredhill.co.uk/CCRAPI/api/\""
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }


    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding = true
        dataBinding = true
        buildConfig = true
    }

    lint {
        abortOnError false
        absolutePaths true
        checkOnly 'NewApi', 'InlinedApi'
        checkAllWarnings true
        checkReleaseBuilds true
        enable 'RtlHardcoded', 'RtlCompat', 'RtlEnabled'
        ignoreWarnings false
        noLines true
        quiet true
        warningsAsErrors true
    }
}

dependencies {
    implementation google.coreKtx
    implementation google.appCompat
    implementation google.googleMaterial
    implementation google.constraintlayout
    implementation google.fragmentKtx
    implementation google.gson
    implementation google.navigation_fragment_ktx
    implementation google.navigation_ui_ktx

    //Epoxy
    implementation epoxy.epoxyRecyclerView
    ksp epoxy.epoxyRecyclerViewProcessor

    //EncryptedSharedPreferences
    implementation google.encryptedPreference

    implementation google.lifecycle_extensions_viewmodel
    implementation google.lifecycle_livedata
    implementation google.lifecycle_process

    //Reactive
    implementation reactive.java
    implementation reactive.android

    //DI
    implementation google.hiltAndroid
    kapt google.hiltAndroidCompiler
    implementation google.hiltWork

    //Retrofit & OkHttp
    implementation square.retrofit
    implementation square.retrofitRxAdapter
    implementation square.okhttpLogging
    implementation square.moshi
    implementation square.moshiConverter
    ksp square.moshiCodeGen

    implementation intuit.sdp
    implementation intuit.ssp

    implementation google.locationService

    implementation 'androidx.work:work-runtime-ktx:2.8.1'

    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.4.0'

    detektPlugins 'io.gitlab.arturbosch.detekt:detekt-formatting:1.23.8'
}

kapt {
    correctErrorTypes true
}

detekt {
    config = files("$rootDir/detekt-config.yml")
    autoCorrect = true
    allRules = false
    parallel = true
    buildUponDefaultConfig = true
}

tasks.withType(Detekt).configureEach {
    jvmTarget = "17"

    reports {
        html {
            required.set(true)
            outputLocation.set(file("$buildDir/reports/detekt/detektAll.html"))
        }
        txt {
            required.set(true)
        }
    }
}

//tasks.register('detektAll', Detekt) {
//
////    def allKotlinSources = subprojects.collect { subproject ->
////        [
////                file("${subproject.projectDir}/src/main/kotlin"),
////                file("${subproject.projectDir}/src/main/java")
////        ]
////    }.flatten()
////
////    setSource(files(allKotlinSources))
//    config = files("$rootDir/detekt-config.yml")
//
//
////    include("**/*.kt", "**/*.kts")
////    exclude("**/resources/**", "**/build/**")
//
//    reports {
//        html {
//            required.set(true)
//            outputLocation.set(file("$buildDir/reports/detekt/detektAll.html"))
//        }
//        txt {
//            required.set(true)
//        }
//    }
//}