name: pull-request-verify
on:
  pull_request:
    branches:
      - develop
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check Lint
        run: |
          chmod +x gradlew && ./gradlew lint
          
      - name: Check KTLint
        run: |
          chmod +x gradlew && ./gradlew ktlint
          
      - name: Check KTLintFormat
        run: |
          chmod +x gradlew && ./gradlew ktlintFormat
          
      - name: Run detekt (Coding Standards Check)
        run: |
          chmod +x gradlew && ./gradlew detekt

      - name: Check for forbidden words
        run: |
          echo "Checking for forbidden words like 'testing', 'staging', 'dummy'..."
          forbidden_words=("testing" "staging" "dummy")
          files_changed=$(git diff --name-only origin/${{ github.base_ref }})
          
          for file in $files_changed; do
            if [[ $file == *.kt ]]; then
              for word in "${forbidden_words[@]}"; do
                if grep -i -n "$word" "$file"; then
                  echo "::error file=$file::Forbidden word '$word' found. Please remove it."
                  exit 1
                fi
              done
            fi
          done

      - name: Upload reports (optional)
        uses: actions/upload-artifact@v2
        with:
          name: lint-detekt-reports
          path: app/build/reports/
