name: pull-request-android-build-check-ktlint-ktlintFormat
on:
  pull_request:
    branches:
      - develop
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Ktlint and KtlintFormat
        run: |
          chmod +x gradlew && ./gradlew ktlint && ./gradlew ktlintFormat
