name: pull-request-verify
on:
  pull_request:
    branches:
      - develop
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Lint
        run: |
          chmod +x gradlew && ./gradlew lint
      - name: Check KTLint
        run: |
          chmod +x gradlew && ./gradlew ktlint
      - name: Check KTLintFormat
        run: |
          chmod +x gradlew && ./gradlew ktlintFormat
