name: pull-request-android-build
on:
  pull_request:
    branches:
      - develop
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Android Release
        run: |
          chmod +x gradlew && ./gradlew assembleDebug
